// <auto-generated />
using System;
using System.Collections.Generic;
using Aatrox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Aatrox.Data.Migrations
{
    [DbContext(typeof(AatroxDbContext))]
    [Migration("20190709142816_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Aatrox.Data.Entities.GuildEntity", b =>
                {
                    b.Property<decimal>("Id")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 20, scale: 0)))
                        .HasColumnName("snowflake_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<List<string>>("Prefixes")
                        .HasColumnName("prefixes");

                    b.HasKey("Id");

                    b.ToTable("guild_entity");
                });
#pragma warning restore 612, 618
        }
    }
}
